### ISSUE TITLE
Mark as done

### ISSUE THREAD

**Issue by smangold459** [learn-co-curriculum/dsc-data-viz-cumulative-lab#1]
Should I be able to mark this lab completed or is it tied to the post test?

**Comment by hoffm386** [comment]
@smangold459 this looks like a Canvas issue rather than a GitHub issue. In the future it would be helpful to share something like this on Slack as well!

Marking complete helps us track your progress but isn't necessary for passing the course; the post test is what determines if you pass. In this case it looks like it was misconfigured in Canvas but that shouldn't get in the way of your progress. (I can see that you made it past prework already, nice!)
